name: Automated Deployment to AWS S3 and CloudFront

on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Choose the environment for deployment'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - qa
          - prod

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"
    environment: ${{ github.event.inputs.environment || 'dev' }}
    env:
      VITE_ROLES: ${{ vars.VITE_ROLES }}
      VITE_CLOUDFRONT_URL: ${{ vars.VITE_CLOUDFRONT_URL }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js and pnpm
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install Dependencies
        run: pnpm install

      - name: Build Application
        run: pnpm run build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Sync files to S3
        run: |
          echo "Deploying to bucket ${{ vars.BUCKET_NAME }}/"
          aws s3 sync ./dist s3://${{ vars.BUCKET_NAME }}/ --delete
